Repository swaaz/basicprograms, pull requests merged in 2020-10, with the labels that each got.

#88 Hacktoberfest
  C/program-1/a.out
  C/program-15/a.out
  C/program-16/.vscode/launch.json
  C/program-16/a.out
  C/program-17/a.out
  C/program-18/program.c
  C/program-19/a.out
  C/program-20/a.out
  C/program-21/a.out
  C/program-22/a.out
  C/program-23/a.out
  C/program-24/a.out
  C/program-25/a.out
  C/program-26/a.out
  C/program-27/a.out
  C/program-28/a.out
  C/program-29/a.out
  C/program-30/a.out
  C/program-31/a.out
  C/program-31/program.c
  C/program-32/program.c
  C/program-33/program.c
  C/program-37/a.out
  C/program-37/program.c
  C/program-38/a.out
  C/program-38/program.c
  C/program-39/a.out
  C/program-39/program.c
  C/program-40/program.c
  C/program-42/program.c
  C/program-43/program.c
  C/program-44/program.c
  Java/program-1/README.md
  Java/program-1/program.java
Labels: Hacktoberfest

#90 Hacktoberfest
  C/program-51/README.md
  C/program-51/program.c
Labels: Hacktoberfest

#79 Added a python program
  Python/Program-3/README.md
  Python/Program-3/program.py
Labels: Hacktoberfest

#81 Created branchT-4
  C/program-54/Readme.md
  C/program-54/program.c
Labels: Hacktoberfest

#91 Hacktoberfest
  C/program-48/README.md
  C/program-48/program.c
Labels: Hacktoberfest

#82 Add program-55
  C/program-55/program.c
  C/program-55/read.md
Labels: Hacktoberfest

#80 Added a program in C
  C/program-56/README.md
  C/program-56/program.c
Labels: Hacktoberfest

#93 Hacktoberfest
  C/program-56/README.md
  C/program-56/program.c
  Javascript/program-2/read.md
  Javascript/program-3/armstrong.html
  Javascript/program-3/read.md
  Javascript/program-4/palindrome.html
  Javascript/program-4/read.md
Labels: Hacktoberfest

#87 Added Program 2 in java
  Java/program-2/README.md
  Java/program-2/program.java
Labels: Hacktoberfest

#89 Program to find number of occurrence in Array in CPP
  C++/Program-2/Readme.md
  C++/Program-2/number_of_occurrence.cpp
  C++/Program-3/Readme.md
  C++/Program-3/swap_kth_Element.cpp
Labels: Hacktoberfest

#92 Added sorting algorithm
  Python/program-4/sorting.py
Labels: Hacktoberfest

#94 Added some programs
  C/README.md
  C/program-47/program 47.c
  Python/program-4/Program 4.py
Labels: Hacktoberfest

#99 Update contribution.md
  .github/ISSUE_TEMPLATE/contribution.md
Labels: Hacktoberfest

#100 Write a program in C to calculate the grade example
  C/program-57/READEME.md
  C/program-57/program.c
Labels: Hacktoberfest

#101 New javascript programs added
  Javascript/program-3/program-3.html
  Javascript/program-4/program-4.html
  Javascript/program-5/program-5.html
  Javascript/program-5/read.md
  Javascript/program-6/program-6.html
  Javascript/program-6/read.md
Labels: Hacktoberfest

#109 Hacktoberfest
  C/README.md
  C/program-25/readme.md
  C/program-47/program 47.c
  C/program-53/Readme.md
  C/program-55/readme.md
  C/program-57/readme.md
  C/program-58/Program.c
  C/program-58/readme.md
  C/program-59/program.c
  C/program-59/readme.md
  C/program-60/program.c
  C/program-60/readme.md
  Java/program-2/README.md
  Java/program-2/program.java
  Javascript/program-3/program-3.html
  Javascript/program-4/program-4.html
  Javascript/program-5/program-5.html
  Javascript/program-5/read.md
  Javascript/program-6/program-6.html
  Javascript/program-6/read.md
  Python/program-4/Program 4.py
Labels: Hacktoberfest

#112 Create factorial.py
  Python/program-5/README.md
  Python/program-5/factorial.py
Labels: Hacktoberfest

#131 Hacktoberfest
  Python/program-4/README.md
  Python/program-4/triangle.py
Labels: Hacktoberfest

#119 Added a program in java
  Java/program-3/README.md
  Java/program-3/program.java
Labels: Hacktoberfest

#132 Hacktoberfest
  Java/program-3/README.md
  Java/program-3/program.java
Labels: Hacktoberfest

#122 Added a c++ program
  C++/Program-4/README.md
  C++/Program-4/program.cpp
Labels: Hacktoberfest

#135 Hacktoberfest
  C++/Program-4/README.md
  C++/Program-4/program.cpp
Labels: Hacktoberfest

#136 Hacktoberfest
  C++/Program-5/Readme.md
  C++/Program-5/program.cpp
Labels: Hacktoberfest

#125 new javascript programs added
  Javascript/program-6/read.md
  Javascript/program-7/program-7.html
  Javascript/program-7/read.md
  Javascript/program-8/program-8.html
  Javascript/program-8/read.md
Labels: Hacktoberfest

#128 added program
  Python/program-10/armstrong.py
Labels: Hacktoberfest

#134 Program to calculate factorial of a number in C++
  C++/Program-4/factorial.cpp
  C++/Program-4/readme.md
Labels: Hacktoberfest

#153 update
  C++/Program-4/README.md
  C++/Program-4/factorial.cpp
  C++/Program-4/program.cpp
  C++/Program-4/readme.md
  C++/Program-5/Readme.md
  C++/Program-5/program.cpp
  C/README.md
  C/program-25/readme.md
  C/program-47/program 47.c
  C/program-53/Readme.md
  C/program-55/readme.md
  C/program-57/program.c
  C/program-57/readme.md
  C/program-58/Program.c
  C/program-58/readme.md
  C/program-59/program.c
  C/program-59/readme.md
  C/program-60/program.c
  C/program-60/readme.md
  C/program-61/program.c
  C/program-63/program.c
  Java/program-2/README.md
  Java/program-2/program.java
  Java/program-3/README.md
  Java/program-3/program.java
  Javascript/program-3/program-3.html
  Javascript/program-4/program-4.html
  Javascript/program-5/program-5.html
  Javascript/program-5/read.md
  Javascript/program-6/program-6.html
  Javascript/program-6/read.md
  Python/program-10/armstrong.py
  Python/program-11/shufflecards.py
  Python/program-4/Program 4.py
  Python/program-4/README.md
  Python/program-4/triangle.py
  Python/program-5/README.md
  Python/program-5/factorial.py
  Python/program-5/pattern.py
  Python/program-6/README.md
  Python/program-6/pattern.py
  Python/program-6/program.py
  Python/program-7/pattern3.py
  Python/program-7/readme.md
  Python/program-8/pattern4.py
  Python/program-8/readme.md
  readme.md
Labels: Hacktoberfest

#154 Swaaz
  gif/giphy.gif
  readme.md
Labels: Hacktoberfest

#151 Key3
  Python/program-14/git.py
  Python/program-14/readme.md
  Python/program-15/git1.py
  Python/program-15/readme.md
  Python/program-16/git2.py
  Python/program-16/readme.md
  Python/program-18/git3.py
  Python/program-18/readme.md
Labels: Hacktoberfest

#162 Updated readme
  readme.md
Labels: Hacktoberfest

#163 Hacktoberfest
  readme.md
Labels: Hacktoberfest

#124 added pattern.py
  Python/program-17/program.py
  Python/program-17/readme.md
  Python/program-18/program.py
  Python/program-18/readme.md
Labels: Hacktoberfest, hacktoberfest-accepted

#142 Add program
  C/Program-61/program.c
  C/README.md
Labels: hacktoberfest-accepted

#164 New javascript programs added
  Javascript/program-10/program-10.html
  Javascript/program-10/read.md
  Javascript/program-9/program-9.html
  Javascript/program-9/read.md
Labels: hacktoberfest-accepted

#166 New program
  Python/README.md
  Python/program-17/program.py
Labels: hacktoberfest-accepted

#167 branchT-8
  C++/Program-6/Readme.md
  C++/Program-6/program.cpp
Labels: hacktoberfest-accepted

#169 update
  C++/Program-6/Readme.md
  C++/Program-6/program.cpp
  C/Program-61/program.c
  C/README.md
  Java/program-3/program.java
  Javascript/program-10/program-10.html
  Javascript/program-10/read.md
  Javascript/program-9/program-9.html
  Javascript/program-9/read.md
  Python/program-17/program.py
  Python/program-17/readme.md
  Python/program-18/program.py
  Python/program-18/readme.md
  Python/program-19/program.py
  Python/program-19/readme.md
  readme.md
Labels: hacktoberfest-accepted

#170 Updated README.md
  C/program-61/program.c
  Python/README.md
  Python/program-17/program.py
  Python/program-17/readme.md
  Python/program-18/program.py
  Python/program-18/readme.md
  Python/program-19/program.py
  Python/program-19/readme.md
  Python/program-20/program.py
Labels: hacktoberfest-accepted

#171 Added program
  C++/Program-7/program.cpp
  C++/Program-7/readme.md
Labels: hacktoberfest-accepted

#172 Hacktoberfest
  C++/Program-7/program.cpp
  C++/Program-7/readme.md
  C/program-61/program.c
  Python/README.md
  Python/program-17/program.py
  Python/program-17/readme.md
  Python/program-18/program.py
  Python/program-18/readme.md
  Python/program-19/program.py
  Python/program-19/readme.md
  Python/program-20/program.py
Labels: hacktoberfest-accepted

#176 Added new programs
  Python/README.md
  Python/program-19/program.py
  Python/program-20/program.py
Labels: hacktoberfest-accepted

#177 Hacktoberfest
  Python/README.md
  Python/program-19/program.py
  Python/program-20/program.py
Labels: hacktoberfest-accepted

#179 "String Anagram" program with solution in java added
  Java/program-4/README.md
  Java/program-4/program.java
Labels: hacktoberfest-accepted

#181 Hacktoberfest
  C++/Program -1/README.md
  C++/Program-8/README.md
  C++/Program-8/program.cpp
  C/README.md
  C/program-62/program.c
Labels: documentation, hacktoberfest-accepted

#186 Pattern Printing using Kotlin
  kotlin/Program1/README.md
  kotlin/Program1/pattern.kt
Labels: hacktoberfest-accepted

#185 Added c++ program and content table
  C++/Program-3/program.cpp
  C++/Program-4/program.cpp
  C++/Program-4/readme.md
  C++/Program-9/program.cpp
  C++/Program-9/readme.md
  C++/README.md
Labels: hacktoberfest-accepted

#189 added problem-10 and created readme
  C++/Program-10/program.cpp
  C++/Program-10/readme.md
Labels: hacktoberfest-accepted

#190 Updated Readme problem-10
  C++/README.md
Labels: hacktoberfest-accepted

#192 Program11
  C++/Program11/Program11.cpp
  C++/Program11/ReadMe.txt
  C++/program-10/Program10.cpp
  C++/program-10/Readme.txt
Labels: hacktoberfest-accepted

#197 Souravrao
  C++/Program-12/README.md
  C++/Program-12/program.cpp
  C++/Program-13/README.md
  C++/Program-13/program.cpp
  C++/Program-14/README.md
  C++/Program-14/program.cpp
Labels: hacktoberfest-accepted

#198 update
  C++/Program-10/program.cpp
  C++/Program-10/readme.md
  C++/Program-12/README.md
  C++/Program-12/program.cpp
  C++/Program-13/README.md
  C++/Program-13/program.cpp
  C++/Program-14/README.md
  C++/Program-14/program.cpp
  C++/Program11/Program11.cpp
  C++/Program11/ReadMe.txt
  C++/README.md
  C++/program-10/Program10.cpp
  C++/program-10/Readme.txt
Labels: hacktoberfest-accepted

#199 Alternative solution to Problem 4 under JAVA (easier and non case sensitive and non space redundant)
  Java/Program 4 alternative/README.md
  Java/Program 4 alternative/program.java
Labels: hacktoberfest-accepted

#200 Alternative solution to P4-java
  Java/Program 4 alternative/README.md
  Java/Program 4 alternative/program.java
Labels: hacktoberfest-accepted

#208 More Mathematical problems in Java
  Java/Program 5/README.md.txt
  Java/Program 5/program.java.txt
  Java/Program 6/README.md.txt
  Java/Program 6/program.java.txt
Labels: Hacktoberfest, hacktoberfest-accepted

#214 Hacktoberfest
  Java/Program 5/README.md.txt
  Java/Program 5/program.java.txt
  Java/Program 6/README.md.txt
  Java/Program 6/program.java.txt
Labels: Hacktoberfest, hacktoberfest-accepted

#209 Add files via upload
  Python/Program 22/Program 22.py.txt
  Python/Program 22/README.md.txt
  Python/Program 23/Program 23.py.txt
  Python/Program 23/README.md.txt
  Python/Program 24/Program 24.txt
  Python/Program 24/README.md.txt
  Python/Program 25/Program 25.py.txt
  Python/Program 25/README.md.txt
  Python/Program 26/Program 26.py.txt
  Python/Program 26/README.md.txt
  Python/Program 27/Program 27.txt
  Python/Program 27/README.md.txt
  Python/Program 28/Program 28.txt
  Python/Program 28/README.md.txt
Labels: Hacktoberfest, hacktoberfest-accepted

#215 Hacktoberfest
  Python/Program 22/Program 22.py.txt
  Python/Program 22/README.md.txt
  Python/Program 23/Program 23.py.txt
  Python/Program 23/README.md.txt
  Python/Program 24/Program 24.txt
  Python/Program 24/README.md.txt
  Python/Program 25/Program 25.py.txt
  Python/Program 25/README.md.txt
  Python/Program 26/Program 26.py.txt
  Python/Program 26/README.md.txt
  Python/Program 27/Program 27.txt
  Python/Program 27/README.md.txt
  Python/Program 28/Program 28.txt
  Python/Program 28/README.md.txt
Labels: Hacktoberfest, hacktoberfest-accepted

#191 program 10
  C++/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#216 Add files via upload
  Python/Program 29/Program 29.py
  Python/Program 29/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#217 Hacktoberfest
  Python/Program 29/Program 29.py
  Python/Program 29/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#219 added new program and altered file name
  C++/Program-16/README.md
  C++/Program-16/rightangle.cpp
  C++/Program-17/README.md
  C++/Program-17/randomcolorscreen.cpp
  C++/Program-18/README.md
  C++/Program-18/getWeekday.cpp
  C++/README.md
  C/program-49/README.md
  C/program-49/program.c
  C/program-52/README.md
  C/program-52/program.c
  C/program-67/program.c
  C/program-68/program-68.c
  C/program-68/readme.md
  Python/Program-22/Plot_function
  Python/Program-22/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#218 Add files via upload
  Python/Program 31/Program 31.py
  Python/Program 31/README.m
Labels: Hacktoberfest, hacktoberfest-accepted

#221 Hacktoberfest
  Python/Program 31/Program 31.py
  Python/Program 31/README.m
Labels: Hacktoberfest, hacktoberfest-accepted

#222 ADDED PGM 63
  C/program-63/README.md
  C/program-63/program.c
  C/program-68/program-68.c
Labels: Hacktoberfest, hacktoberfest-accepted

#223 Hacktoberfest
  C/program-63/README.md
  C/program-63/program.c
  C/program-68/program-68.c
Labels: Hacktoberfest, hacktoberfest-accepted

#224 added new programs and readme files
  C/README.md
  C/program-3/README.md
  C/program-4/README.md
  C/program-5/README.md
  C/program-6/README.md
  C/program-65/README.md
  C/program-65/program.c
  C/program-69/README.md
  C/program-69/strongNumber.c
Labels: Hacktoberfest, hacktoberfest-accepted

#225 Hacktoberfest
  C/README.md
  C/program-3/README.md
  C/program-4/README.md
  C/program-5/README.md
  C/program-6/README.md
  C/program-65/README.md
  C/program-65/program.c
  C/program-69/README.md
  C/program-69/strongNumber.c
Labels: Hacktoberfest, hacktoberfest-accepted

#226 altered file
  C/README.md
  C/program-1/README.md
  C/program-10/README.md
  C/program-11/README.md
  C/program-12/README.md
  C/program-13/README.md
  C/program-14/README.md
  C/program-17/README.md
  C/program-18/README.md
  C/program-2/README.md
  C/program-7/README.md
  C/program-8/README.md
  C/program-8/program.c
  C/program-9/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#227 Hacktoberfest
  C/README.md
  C/program-1/README.md
  C/program-10/README.md
  C/program-11/README.md
  C/program-12/README.md
  C/program-13/README.md
  C/program-14/README.md
  C/program-17/README.md
  C/program-18/README.md
  C/program-2/README.md
  C/program-7/README.md
  C/program-8/README.md
  C/program-8/program.c
  C/program-9/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#228 Program to Print series of (3n+2).
  C++/Program18/PrintSeries.cpp
  C++/Program18/Readme.md
Labels: Hacktoberfest, hacktoberfest-accepted

#229 Mayanksingla139 added palindrome program in c++
  C++/README.md
  C++/program-19/Read me.md
  C++/program-19/palindrome.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#230 Update README.md
  Python/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#231 Update README.md
  Python/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#232 Update README.md
  Python/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#233 Implementation of Binary Search
  C++/Program-20/README.md
  C++/Program-20/program.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#234 A program in Dart
  Dart/Program1/README.md
  Dart/Program1/checkevenodd.dart
Labels: Hacktoberfest, hacktoberfest-accepted

#235 Added Program 30 in Python folder
  Python/Program 30/README.md
  Python/Program 30/program.py
  Python/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#236 Added program 70 in C folder
  C/README.md
  C/program-70/README.md
  C/program-70/program70.c
Labels: Hacktoberfest, hacktoberfest-accepted

#237 Addition of new program in C++ directory
  C++/Program-21/README.md
  C++/Program-21/program.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#238 Added Binary String Addition Algorithm
  C++/Program 22/adding_two_string.cpp
  C++/Program 22/readme.md
  C++/Program 23/readme.md
  C++/Program 23/sum_of_square_of_binomial_coefficient.cpp
Labels: Hacktoberfest, hacktoberfest-accepted

#239 update
  C++/Program 22/adding_two_string.cpp
  C++/Program 22/readme.md
  C++/Program 23/readme.md
  C++/Program 23/sum_of_square_of_binomial_coefficient.cpp
  C++/Program-20/README.md
  C++/Program-20/program.cpp
  C++/Program-21/README.md
  C++/Program-21/program.cpp
  C++/Program18/PrintSeries.cpp
  C++/Program18/Readme.md
  C++/README.md
  C++/program-19/Read me.md
  C++/program-19/palindrome.cpp
  C/README.md
  C/program-70/README.md
  C/program-70/program70.c
  Dart/Program1/README.md
  Dart/Program1/checkevenodd.dart
  Python/Program 30/README.md
  Python/Program 30/program.py
  Python/README.md
  readme.md
Labels: Hacktoberfest, hacktoberfest-accepted

#240 program added
  Java/program-7/README.md
  Java/program-7/program.java
Labels: Hacktoberfest, hacktoberfest-accepted

#241 created python/program-32
  Python/program-32/program.py
  Python/program-32/readme.md
Labels: Hacktoberfest, hacktoberfest-accepted

#243 Update README.md
  C++/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#244 Update README.md
  Python/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#245 added readme.md
  Dart/README.md
  kotlin/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#249 added javascript/program-11
  C++/README.md
  Dart/README.md
  Javascript/program-11/program.js
  Javascript/program-11/readme.md
  Python/README.md
  kotlin/README.md
Labels: Hacktoberfest, hacktoberfest-accepted

#250 Hacktoberfest
  Javascript/program-11/program.js
  Javascript/program-11/readme.md
Labels: Hacktoberfest, hacktoberfest-accepted
